spring:
  application:
    name: BlogManagement

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5433/BlogManagement

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/BlogManagement

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

info:
  app:
    name: BlogManagement
    version: 1.0.0
    description: "This is my blog management app"
  developer:
    name: Nadine

server:
  port: 8088